"""Golden-dataset record schema.

Richer than a bare (question, gold_urls) pair on purpose: the metadata is what
lets the evaluation slice results by intent, budget-constraint, source and
difficulty instead of reporting one averaged number that hides everything.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class QuerySource(StrEnum):
    """Where the query text came from. Reported per-slice; see eval/README.md.

    This project has **no access to production traffic, support tickets or
    site search logs** — it evaluates a publicly crawled third-party catalogue.
    Rather than invent "real user queries", the provenance of every query is
    recorded so a reader can weight the evidence themselves.
    """

    # Real aggregated user queries mined from search-engine autocomplete for
    # Vietnamese flower-buying seeds. The closest legitimate proxy for
    # production traffic available here: these strings are what people actually
    # typed, including the typos, budget phrasings and out-of-area requests.
    AUTOCOMPLETE = "autocomplete"

    # The 8 canned questions shipped in the original app's sidebar — the shop
    # author's own model of what customers ask.
    APP_SIDEBAR = "app_sidebar"

    # Generated by an LLM from product records. Weakest provenance: prone to
    # echoing document wording, which inflates retrieval scores. Filtered for
    # title leakage and reported as its own slice.
    SYNTHETIC = "synthetic"

    # Written by hand during annotation.
    MANUAL = "manual"


class Intent(StrEnum):
    PRODUCT_SEARCH = "product_search"  # "bó hoa sinh nhật cho nữ"
    BUDGET_SEARCH = "budget_search"  # "hoa khai trương 500k"
    ATTRIBUTE = "attribute"  # "hoa lan hồ điệp màu trắng"
    POLICY = "policy"  # "có freeship không", "giao bao lâu"
    OUT_OF_CATALOGUE = "out_of_catalogue"  # "shop hoa tươi cần thơ"
    OFF_TOPIC = "off_topic"  # "hoa tặng mẹ bài đọc lớp 4"


class GoldenQuery(BaseModel):
    id: str
    question: str

    # Empty list means the system is expected to abstain. Distinguishing "no
    # correct product exists" from "we failed to find it" is the whole point of
    # the abstention metric.
    gold_urls: list[str] = Field(default_factory=list)
    answerable: bool = True

    source: QuerySource
    intent: Intent

    # --- optional structured facets, used for slicing ---
    occasion: str | None = None  # sinh nhật, khai trương, chia buồn, ...
    recipient: str | None = None  # mẹ, người yêu, nam, nữ, ...
    flower_type: str | None = None  # hồng, lan hồ điệp, cẩm tú cầu, ...
    budget_max_vnd: int | None = None
    form_factor: str | None = None  # bó, giỏ, kệ, chậu

    # Reference answer. Required for RAGAS Context Recall, and expensive to
    # write, so it is only populated for the RAGAS subset (see plan §4.1).
    ground_truth: str | None = None
    in_ragas_subset: bool = False

    # Annotation bookkeeping.
    labelled_by: str = "auto"  # auto | human
    reviewed: bool = False
    notes: str | None = None

    def slice_keys(self) -> dict[str, str]:
        """Facets this query contributes to in the sliced report."""
        return {
            "source": self.source.value,
            "intent": self.intent.value,
            "answerable": str(self.answerable),
            "has_budget": str(self.budget_max_vnd is not None),
        }
